name: Update Publications

on:
  schedule:
    - cron: '0 3 * * 0'  # 毎週日曜 3:00 UTC（日本時間12:00）
  workflow_dispatch:

jobs:
  update-publications:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.2

      - name: Install dependencies
        run: pip install google-search-results python-dotenv

      - name: Run publication updater
        env:
          API_KEY: ${{ secrets.API_KEY }}
          GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}
        run: python update_publications.py

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/journal_list.json data/update_date.txt templates/domestic_conference.html templates/domestic_journal.html templates/international_conference.html templates/international_journal.html
          git commit -m "Update publications" || echo "No changes to commit"
          git push
